Repository Majorfolio/majorfolio-frontend, pull requests merged in 2024-01, with the labels that each got.

#2 Landing Page
  majorfolio/src/assets/images/landing/landing-bell.png
  majorfolio/src/assets/images/landing/landing-calendar.png
  majorfolio/src/assets/images/landing/landing-clipboard.png
  majorfolio/src/assets/images/landing/landing-clock.png
  majorfolio/src/assets/images/landing/landing-curve.svg
  majorfolio/src/assets/images/landing/landing-dollar.png
  majorfolio/src/assets/images/landing/landing-dotline.svg
  majorfolio/src/assets/images/landing/landing-icon1.svg
  majorfolio/src/assets/images/landing/landing-icon2.svg
  majorfolio/src/assets/images/landing/landing-icon3.svg
  majorfolio/src/assets/images/landing/landing-icon4.svg
  majorfolio/src/assets/images/landing/landing-logo.svg
  majorfolio/src/assets/images/landing/landing-mf1.svg
  majorfolio/src/assets/images/landing/landing-mf2.svg
  majorfolio/src/assets/images/landing/landing-mf3.svg
  majorfolio/src/assets/images/landing/landing-mf4.svg
  majorfolio/src/assets/images/landing/landing-pencil.png
  majorfolio/src/assets/images/landing/landing-phone1.png
  majorfolio/src/assets/images/landing/landing-phone1.svg
  majorfolio/src/assets/images/landing/landing-phone2.png
  majorfolio/src/assets/images/landing/landing-phone2.svg
  majorfolio/src/assets/images/landing/landing-phone3.png
  majorfolio/src/assets/images/landing/landing-phone3.svg
  majorfolio/src/assets/images/landing/landing-right-chevron.svg
  majorfolio/src/assets/index.js
  majorfolio/src/assets/landing-calendar.svg
  majorfolio/src/assets/landing-clipboard.svg
  majorfolio/src/assets/landing-dollar.svg
  majorfolio/src/assets/landing-pencil.svg
  majorfolio/src/pages/Landing/Landing.jsx
  majorfolio/src/pages/Landing/Landing.module.css
  majorfolio/src/pages/Landing/Landing.styles.jsx
Labels: 이찬양

#11 Fix previous eslint problems
  .gitignore
  majorfolio/.eslintrc
  majorfolio/.prettierrc
  majorfolio/package.json
  majorfolio/src/App.jsx
  majorfolio/src/App.tsx
  majorfolio/src/assets/icons/index.js
  majorfolio/src/index.tsx
  majorfolio/src/stories/AllDivider.stories.js
  majorfolio/src/stories/AllDivider.stories.jsx
  majorfolio/src/stories/AllTagSmall.stories.js
  majorfolio/src/stories/AllTagSmall.stories.jsx
  majorfolio/src/stories/DetailPost.stories.js
  majorfolio/src/stories/DetailPost.stories.jsx
  majorfolio/tsconfig.json
Labels: chores

#12 chores: add eslint rules
  .gitignore
  majorfolio/.eslintrc
  majorfolio/.gitignore
  majorfolio/package-lock.json
  majorfolio/src/assets/icons/ico_bookmark.svg
  majorfolio/src/assets/icons/index.js
  majorfolio/src/components/AllTagSmall/AllTagSmall.jsx
  majorfolio/src/components/DetailPost/DetailPost.jsx
  majorfolio/src/components/DetailProfile/DetailProfile.jsx
  majorfolio/src/components/DetailProfile/DetailProfile.styles.jsx
  majorfolio/src/components/common/AllDivider/AllDivider.styles.tsx
  majorfolio/src/components/common/AllDivider/AllDivider.tsx
  majorfolio/src/components/common/AllTagSmall/AllTagSmall.styles.tsx
  majorfolio/src/components/common/AllTagSmall/AllTagSmall.tsx
  majorfolio/src/components/home/MaterialDetailPost/MaterialDetailPost.styles.tsx
  majorfolio/src/components/home/MaterialDetailPost/MaterialDetailPost.tsx
  majorfolio/src/components/home/MaterialSellerProfile/MaterialSellerProfile.styles.tsx
  majorfolio/src/components/home/MaterialSellerProfile/MaterialSellerProfile.tsx
  majorfolio/src/pages/Landing/Landing.jsx
  majorfolio/src/stories/AllDivider.stories.jsx
  majorfolio/src/stories/AllTagSmall.stories.jsx
  majorfolio/src/stories/MaterialDetailPost.stories.jsx
  majorfolio/src/stories/MaterialSellerProfile.stories.jsx
  majorfolio/tsconfig.json
Labels: chores

#14 Define typography component
  .eslintrc
  .storybook/main.js
  .storybook/main.ts
  .storybook/preview-head.html
  .storybook/preview.js
  .storybook/preview.tsx
  package.json
  public/index.html
  src/App.tsx
  src/components/common/GlobalStyle/index.tsx
  src/components/common/Text/index.styles.tsx
  src/components/common/Text/index.tsx
  src/components/common/Text/index.types.ts
  src/components/common/theme/index.ts
  src/stories/Text.stories.tsx
Labels: enhancement
